version: "3.9"

services:
  db:
    image: mariadb
    container_name: nlw_heat
    restart: always
    ports:
      - 1234:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nlw_heat